

services:

  db:
    image: mysql:latest
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  api:
    build: ./backend
    working_dir: /var/www
    restart: always
    depends_on:
      - "db"
    ports:
      - 8000:8000

  web:
    build: ./frontend
    working_dir: /var/www
    ports:
      - 80:3000
  
volumes:
  dbdata: